const fs = require("fs");

/* ── 1. OfferBanner ── */
fs.writeFileSync("frontend/src/components/common/OfferBanner.jsx", [
  'import React, { useState, useEffect } from "react";',
  'import { Link } from "react-router-dom";',
  'import { offerAPI } from "../../services/api";',
  'import { X } from "lucide-react";',
  '',
  'const OfferBanner = () => {',
  '  const [offer, setOffer] = useState(null);',
  '  const [visible, setVisible] = useState(true);',
  '',
  '  useEffect(() => {',
  '    if (sessionStorage.getItem("offerBannerDismissed") === "true") { setVisible(false); return; }',
  '    offerAPI.getStoreWide()',
  '      .then(res => { const d = res.data || res; if (d && d._id) setOffer(d); })',
  '      .catch(err => console.error("OfferBanner error:", err));',
  '  }, []);',
  '',
  '  const dismiss = () => { setVisible(false); sessionStorage.setItem("offerBannerDismissed","true"); };',
  '',
  '  if (!offer || !visible) return null;',
  '',
  '  const discount = offer.discountType === "percentage" ? offer.discountValue + "%" : "Rs. " + offer.discountValue;',
  '  const scopeText = offer.scope === "entire_store" ? "Sitewide" : offer.scope === "categories" ? "Selected Categories" : "Selected Products";',
  '  const label = "\\uD83C\\uDF89 " + offer.title + "  \u00B7  " + scopeText + " \u2013 Save " + discount + "  \u00B7  Shop Now \u2192";',
  '',
  '  return (',
  '    <div className="relative bg-gradient-to-r from-purple-700 via-pink-600 to-red-600 text-white overflow-hidden">',
  '      <div className="overflow-hidden py-2.5 pr-10">',
  '        <div className="flex whitespace-nowrap" style={{ animation: "marquee 28s linear infinite" }}>',
  '          {[0,1,2,3].map(i => (',
  '            <Link key={i} to={"/offers/" + offer._id}',
  '              className="inline-block px-16 text-sm font-medium hover:opacity-80 transition-opacity">',
  '              {label}',
  '            </Link>',
  '          ))}',
  '        </div>',
  '      </div>',
  '      <button onClick={dismiss} className="absolute right-2 top-1/2 -translate-y-1/2 p-1 rounded-full hover:bg-white/20 transition-colors" aria-label="Dismiss">',
  '        <X size={18} />',
  '      </button>',
  '      <style>{`@keyframes marquee { from { transform: translateX(0) } to { transform: translateX(-50%) } }`}</style>',
  '    </div>',
  '  );',
  '};',
  '',
  'export default OfferBanner;',
].join("\n"), "utf8");
console.log("OK  OfferBanner.jsx");

/* ── 2. AppRoutes ── */
fs.writeFileSync("frontend/src/routes/AppRoutes.jsx", [
  'import { Routes, Route } from "react-router-dom";',
  'import GoogleAuthSuccess from "../pages/public/GoogleAuthSuccess";',
  'import ProtectedRoute from "../components/common/ProtectedRoute";',
  'import AdminRoute from "../components/common/AdminRoute";',
  'import AdminLayout from "../layouts/AdminLayout";',
  'import HomePage from "../pages/public/HomePage";',
  'import ProductsPage from "../pages/public/ProductsPage";',
  'import ProductDetailPage from "../pages/public/ProductDetailPage";',
  'import OfferProductsPage from "../pages/public/OfferProductsPage";',
  'import LoginPage from "../pages/public/LoginPage";',
  'import RegisterPage from "../pages/public/RegisterPage";',
  'import ContactPage from "../pages/public/ContactPage";',
  'import VerifyEmailPage from "../pages/public/VerifyEmailPage";',
  'import DashboardPage from "../pages/user/DashboardPage";',
  'import CartPage from "../pages/user/CartPage";',
  'import CheckoutPage from "../pages/user/CheckoutPage";',
  'import OrdersPage from "../pages/user/OrdersPage";',
  'import OrderDetailPage from "../pages/user/OrderDetailPage";',
  'import ProfilePage from "../pages/user/ProfilePage";',
  'import AdminDashboardPage from "../pages/admin/AdminDashboardPage";',
  'import ManageProductsPage from "../pages/admin/ManageProductsPage";',
  'import ManageCategoriesPage from "../pages/admin/ManageCategoriesPage";',
  'import ManageOrdersPage from "../pages/admin/ManageOrdersPage";',
  'import ManageUsersPage from "../pages/admin/ManageUsersPage";',
  'import ManageContactPage from "../pages/admin/ManageContactPage";',
  'import ManageOffersPage from "../pages/admin/ManageOffersPage";',
  'import SendEmailPage from "../pages/admin/SendEmailPage";',
  '',
  'function AppRoutes() {',
  '  return (',
  '    <Routes>',
  '      <Route path="/" element={<HomePage />} />',
  '      <Route path="/home" element={<HomePage />} />',
  '      <Route path="/products" element={<ProductsPage />} />',
  '      <Route path="/products/:id" element={<ProductDetailPage />} />',
  '      <Route path="/offers/:offerId" element={<OfferProductsPage />} />',
  '      <Route path="/login" element={<LoginPage />} />',
  '      <Route path="/register" element={<RegisterPage />} />',
  '      <Route path="/contact" element={<ContactPage />} />',
  '      <Route path="/verify-email" element={<VerifyEmailPage />} />',
  '      <Route path="/auth/google/success" element={<GoogleAuthSuccess />} />',
  '      <Route path="/dashboard" element={<ProtectedRoute><DashboardPage /></ProtectedRoute>} />',
  '      <Route path="/cart" element={<ProtectedRoute><CartPage /></ProtectedRoute>} />',
  '      <Route path="/checkout" element={<ProtectedRoute><CheckoutPage /></ProtectedRoute>} />',
  '      <Route path="/orders" element={<ProtectedRoute><OrdersPage /></ProtectedRoute>} />',
  '      <Route path="/orders/:id" element={<ProtectedRoute><OrderDetailPage /></ProtectedRoute>} />',
  '      <Route path="/profile" element={<ProtectedRoute><ProfilePage /></ProtectedRoute>} />',
  '      <Route path="/admin" element={<AdminRoute><AdminLayout /></AdminRoute>}>',
  '        <Route index element={<AdminDashboardPage />} />',
  '        <Route path="dashboard" element={<AdminDashboardPage />} />',
  '        <Route path="products" element={<ManageProductsPage />} />',
  '        <Route path="categories" element={<ManageCategoriesPage />} />',
  '        <Route path="orders" element={<ManageOrdersPage />} />',
  '        <Route path="users" element={<ManageUsersPage />} />',
  '        <Route path="contact" element={<ManageContactPage />} />',
  '        <Route path="offers" element={<ManageOffersPage />} />',
  '        <Route path="email" element={<SendEmailPage />} />',
  '      </Route>',
  '    </Routes>',
  '  );',
  '}',
  '',
  'export default AppRoutes;',
].join("\n"), "utf8");
console.log("OK  AppRoutes.jsx");

console.log("\nAll batch-1 files written. Running batch-2 next...");
